Kuadrant/authorino

.github/workflows/code-style.yaml
This PR adds a GitHub action for checking Go code style. 
It's taken directly from the Knative Serving repository. It provides a great starting point to customize it, etc.
=> Github Action - Code style

LICENSE
in line with other 3scale projects
=> Adds apache 2.0 license

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Let's make it easier for folks to report issues in Authorino
=> Add (bug|feature) github issue templates

README.md
=> Fix README: table of features

README.md, examples/echo-api-protection.yaml, pkg/config/authorization/opa.go
=> Remove OPA rego policy template injected variables

README.md, docs/terminology.md
Add an initial terminology.md document in ./docs/
=> Terminology doc

Makefile, api/v1beta1/service_types.go, config/crd/bases/config.authorino.3scale.net_services.yaml, config/crd/kustomization.yaml, config/crd/patches/oneof_in_services.yaml, controllers/service_controller.go, examples/dex/README.md, examples/echo-api-key-simple.yaml, examples/echo-api-kubernetes-auth.yaml, examples/echo-api-protection.yaml, pkg/common/auth_credentials/auth_credentials.go, pkg/config/identity.go, pkg/config/identity/api_key.go
=> CRD's OpenAPI enhancements

pkg/service/auth.go
When trying to authorize a request with HOST:PORT (ex: petstore.127.0.0.1.nip.io:8080) Authorino fails to find a service config that matches. 
This PR tries to retrieve the service config with the incoming Host header, and if that fails, removes the port part (if it exists) from the host header and tries to get a new config.
=> Remove the port part from the host header when looking for a cache service config.

.github/workflows/build-latest.yaml
Builds and pushes to `quay.io/3scale/authorino:latest` on merge to `master`.
Closes #15.
=> GitHub Action to build and push image to quay.io

README.md, docs/deploy.md, docs/tutorials/showcase/README.md, pkg/service/auth_pipeline.go
- Typos
- Markdown style
- Rephrasing couple sentences
=> Fix minor docs issues

controllers/secret_controller.go, controllers/service_controller.go, controllers/service_status_updater.go, deploy/base/leader_election_role.yaml, install/rbac/role.yaml
Add permissions for leader election using K8s `leases.coordination.k8s.io`.
=> Leader election lease permission

README.md
=> Add k8s authz to the summary

controllers/auth_config_controller.go, install/rbac/role.yaml
=> Fix Kubernetes auth permissions for the manager-role

Makefile, install/manifests.yaml, install/rbac/auth_config_editor_role.yaml, install/rbac/auth_config_viewer_role.yaml, install/rbac/kustomization.yaml
=> Manifests bundle

install/crd/patches/oneof_in_authconfigs.yaml, install/manifests.yaml
Fix the OAS patch implemented in #218.
=> Fix OAS required properties for anonymous access

docs/getting-started.md
=> [docs] Small fixes in Getting Started user guide

.github/workflows/e2e-test.yaml
=> Remove auto-trigger of 'End-to-end Tests'

README.md
Access tokens -> Ready
External metadata -> Ready
Policy evaluation -> Ready
=> README update with latest state of caching features

Dockerfile
Architecture and platform inferred from context when building the image
=> [hotfix] Multi-Platform auto build

Dockerfile
Specifying the architecture and platform from arguments when building the image
=> [hotfix] Multi-Platform auto build (2)

main.go
A critical bug was introduced in #273, which made the gRPC server not to be started when TLS is disabled. We did not catch that in the automated integration tests because those run always with TLS enabled.
=> [hotfix] Ensure gRPC server starts when TLS is disabled

Makefile
Make target to install [mock/mockgen](https://github.com/golang/mock/mockgen) in ./bin.
Install:
```sh
make mockgen
```
Use (e.g.):
```sh
./bin/mockgen -source=pkg/auth/auth.go -destination=pkg/auth/mocks/mock_auth.go
```
=> Make mocken

Makefile, docs/contributing.md
- Golang v1.17+
- Dependencies installed with `go install`
- `make help`
- Pro tips
- `TLS_ENABLED`
- `FF=1`
- `DEPLOY_(KEYCLOAK|DEX|IDPS)`
- `port-forward &;PID=$!`
=> Update Developer’s guide

tests/e2e-test.sh
=> e2e enhancements

README.md, docs/architecture.md, docs/getting-started.md
- Getting started page
- Rephrasing a few bits
- Added mention to the Raw HTTP Authorization interface
- New 'Life cycle' subsection (closes #204)
- Highlight of Authorino in the Envoy config
- Fix broken links
- Architecture page
- Raw HTTP Authorization interface
- README
- Enhacements to the summary
- List of highlighted user guides updated
- New entries to the FAQ
- Mention to the Raw HTTP authz interface in 'Do I need to deploy Envoy?'
=> Docs enhancements

Makefile, docs/contributing.md
Required for make targets 'certs' and 'deploy'.
=> Check if GNU sed is installed

docs/user-guides/logging.md, pkg/service/auth.go
This PR introduces a debug logging that it was lacking whenever Authorino was closing the connection and sending back the http status.
=> Logging response error messages

.github/workflows/go-test.yaml, Makefile, README.md, controllers/auth_config_controller_test.go, docs/contributing.md, pkg/evaluators/authorization/json_test.go, pkg/evaluators/authorization/opa_test.go, pkg/evaluators/identity/api_key_test.go, pkg/httptest/http_mocks.go, pkg/service/auth_pipeline_test.go
Adds the following test benchmarks:
- Reconcile an AuthConfig (identity: OIDC; metadata: UserInfo, UMA; authorization: OPA)
- Evaluate the auth pipeline for an AuthConfig (identity: OIDC; authorization: JSON)
- API key authentication
- OPA (inline rego) authorization
- JSON patterm-matching authorization
Use `make benchmarks` to run locally.
Results after any push to remote can be checked in GitHub as well for linux/amd64 – added to 'Unit Tests' GHA workflow.
Latest results added to the README.
```
name                         time/op
ReconcileAuthConfig          1.39ms ± 0%
ReconcileAuthConfig-4        1.32ms ± 0%
ReconcileAuthConfig-10       1.62ms ± 0%
JSONPatternMatchingAuthz     1.68µs ± 0%
JSONPatternMatchingAuthz-4   1.67µs ± 0%
JSONPatternMatchingAuthz-10  1.64µs ± 0%
OPAAuthz …
```
=> Test benchmarks

docs/features.md
Adda a section about deep metrics (i.e. metrics at the level of each evaluator within an AuthConfig) to the Feature description page of the docs.
Closes #316.
=> [docs] Deep metrics

docs/features.md, docs/user-guides/api-key-authentication.md, docs/user-guides/http-basic-authentication.md, docs/user-guides/validating-webhook.md
We left these ones behind after #341.
=> [docs] Fix refs to apiKey.labelSelectors

.github/workflows/code-style.yaml, .github/workflows/e2e-test.yaml, .github/workflows/go-test.yaml, .github/workflows/integration-test.yaml, Dockerfile, docs/contributing.md, docs/user-guides/metrics.md, go.mod, go.sum
=> Upgrade to Golang v1.18.x

pkg/evaluators/metadata/generic_http.go, pkg/evaluators/metadata/generic_http_test.go
So a source of metadata that responds with a JSON such as:
```jsonc
{"foo":"bar"}
{"blah":"bleh"}
```
Results in a metadata object appended to the Authorization JSON as such:
```jsonc
[
{"foo":"bar"},
{"blah":"bleh"}
]
```
...instead of:
```jsonc
{"foo":"bar"}
```
=> Support for multi-element JSON responses from external sources of metadata

go.mod, pkg/service/auth.go, pkg/trace/trace.go
Ensures the Authorino request ID is available. Fetches from the request when available, generates a uuid4 one otherwise.
Precedence:
- gRPC authorization: `x-request-id` → `envoy.service.auth.v3.AttributeContext_HttpRequest id` → uuid4
- Raw HTTP authorization: `x-request-id` → uuid4
Build and run:
```sh
make cluster install build
bin/authorino server
```
Create an AuthConfig that echoes back the request ID in the response:
```sh
kubectl apply -f -<<EOF
metadata:
name: request-id
spec:
hosts:
- localhost
response:
- name: request
json:
properties:
- name: id
valueFrom:
authJSON: context.request.http.id
EOF
```
In a separate shell, send requests with and without request id:
```sh
curl -H "X-Request-Id: …
```
=> Ensure request id

docs/code_of_conduct.md
CoC updated to point to Kuadrant's
=> CoC update

Makefile, install/crd/authorino.kuadrant.io_authconfigs.yaml, install/manifests.yaml, install/rbac/role.yaml
Similar to https://github.com/Kuadrant/authorino-operator/pull/188 - Fixes a sigsegv when running `make manifests`
=> Update controller-gen to v0.15.0

README.md
=> fix smoketest link

api/v1beta2/auth_config_types.go, api/v1beta3/auth_config_types.go, install/crd/authorino.kuadrant.io_authconfigs.yaml, install/manifests.yaml
=> spelling fixes in crs

Makefile, deploy/authorino.yaml, docs/contributing.md
Add support for Podman for developers.
=> Support for Podman

docs/features.md, pkg/expressions/cel/expressions.go, pkg/expressions/cel/expressions_test.go, tests/v1beta3/authconfig.yaml
Closes: https://github.com/Kuadrant/authorino/issues/556
=> feat: allow cel optional syntax
