Kuadrant/authorino

config/rbac/role.yaml
controllers/service_controller.go

By adding those perms we ensure that the code generation will recreate the role.yaml file properly

Specifies missing secrets perms for kubebuilder codegen

---

pkg/config/authorization.go
pkg/config/authorization/jwt.go
pkg/config/authorization/opa.go
pkg/config/common/auth_context.go
pkg/config/identity.go
pkg/config/identity/api_key.go
pkg/config/identity/hmac.go
pkg/config/identity/mtls.go
pkg/config/identity/oidc.go
pkg/config/metadata.go
pkg/config/metadata/uma.go
pkg/config/metadata/user_info.go

As a rule proposed in Go 1.4 and applied when vendoring was added in Go 1.5:
> An import of a path containing the element “internal” is disallowed if the importing code is outside the tree rooted at the parent of the “internal” directory.
Also, to avoid build failures such as:

Renaming `config/internal` package to `config/common`

---

controllers/service_controller.go
go.mod
go.sum
pkg/config/authorization.go
pkg/config/common/auth_context.go
pkg/config/config.go
pkg/config/identity.go
pkg/config/metadata.go
pkg/service/auth.go
pkg/service/auth_context.go
vendor/golang.org/x/sync/AUTHORS
vendor/golang.org/x/sync/CONTRIBUTORS
vendor/golang.org/x/sync/LICENSE
vendor/golang.org/x/sync/PATENTS
vendor/golang.org/x/sync/errgroup/errgroup.go
vendor/modules.txt

This PR implements a concurrent way of getting Auth objects, instead of getting them in sequential order.
Fixes https://github.com/3scale-labs/authorino/issues/27
Notes:
No tests. A following refactor of the different auth config objects is needed first, in order to avoid converting this into massive refactor PR.

Concurrent authcontext calls

---

README.md
pkg/service/auth.go
pkg/service/auth_test.go

Fixes the RPC to HTTP status code mapping so, instead of HTTP `401 Unauthorized`, it will now do proper mapping:
| GRPC | HTTP |
|-------|-------|
| FAILED_PRECONDITION | 400 Bad request |
| NOT_FOUND | 404 Not found |
| PERMISSION_DENIED | 403 Forbidden |
It also modifies so Authorino no longer returns the reason for the auth failure when NOK in the response body as before. Instead, it will now pass the reason in the HTTP response header `x-ext-auth-reason`. This header was previously always filled with the fixed value "forbidden" in such cases.

Fix AuthService RPC x HTTP status code mapping

---

Makefile
utils/local-deploy.sh

Make target to ease rebuilding and redeploying Authorino to the local Kubernetes cluster

make local-deploy

---

api/v1beta1/service_types.go
config/crd/bases/config.authorino.3scale.net_services.yaml

Both are part of `Credentials` type.

[Fix] Removes `Location` and `KeySelector` from APIKey Identity

---

controllers/secret_controller.go
controllers/secret_controller_test.go
examples/echo-api-key-simple.yaml
main.go

Closes #65
----
Introduces the requirement for k8s secrets meant for being used as API keys to always include a label `authorino.3scale.net/managed-by` (with whatever non-null value). Consequently, all services configured for API key authentication must as well include in its `label_selectors` of the `api_key` identity config this new label `authorino.3scale.net/managed-by` (with value matching the one used in the secrets).
A limitation of the implementation here presented is that deleted secrets trigger the reconciler but cannot be checked for matching labels and corresponding affected services. This makes a bit harder for the revoking of access to services by deleting the secrets. Two possible workarounds to this limitation are:
- i) first update the secret before deleting it (i.e. …

K8s secret reconciler

---

examples/echo-api-key-simple.yaml
pkg/common/auth_credentials/auth_credentials.go
pkg/common/auth_credentials/auth_credentials_test.go

This PR extends the feature introduced by https://github.com/3scale-labs/authorino/pull/58 with the option of sending credentials in a Cookie header as described in https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie
The config for this would look like:
```yaml
...
identity:
- name: vip
api_key:
label_selectors:
authorino.3scale.net/managed-by: authorino
target: echo-api
credentials:
in: cookie
key_selector: API-KEY
...
```

Credentials in cookies

---

controllers/service_controller.go
pkg/common/auth_credentials/auth_credentials.go
pkg/common/auth_credentials/auth_credentials_test.go

Closes https://github.com/3scale-labs/authorino/issues/71
* default KeySelector is `Bearer`
* default In (location) is `authorization_header`

Auth Credentials: Default values

---

api/v1beta1/service_types.go
config/crd/bases/config.authorino.3scale.net_services.yaml
controllers/service_controller.go
controllers/service_controller_test.go
examples/echo-api-protection.yaml
go.mod
go.sum
pkg/common/mocks/http_mocks.go
pkg/config/metadata/uma.go
pkg/config/metadata/uma_test.go
pkg/config/metadata/user_info_test.go

Changes the UMA metadata config from this:
```yaml
identity:
- name: auth-server
oidc:
endpoint: http://auth-server
metadata:
- uma:
identitySource: auth-server
credentialsRef:
name: umacredentialssecret
```
to this:
```yaml
metadata:
- uma:
endpoint: http://auth-server
credentialsRef:
name: umacredentialssecret
```
Closes #75
----
We didn't have tests for the UMA metadata module yet, so the PR also introduces some. Together with the new tests, there is also a new HTTP server mock helper that makes it easy to map expected HTTP request paths and correspondig responses.

UMA metadata independent from OIDC identity config

---

Makefile

We forgot to make the `vendor` target PHONY, so it was conflicting with the `/vendor` directory.
Also adding `go mod tidy -v` to it.

Fix make vendor target

---

examples/README.md

More enhancements to the examples page

---

pkg/cache/cache_test.go
pkg/common/auth.go
pkg/common/mocks/mock_common.go
pkg/config/authorization.go
pkg/config/authorization/json.go
pkg/config/authorization/json_test.go
pkg/config/authorization/opa.go
pkg/config/identity.go
pkg/config/identity/api_key.go
pkg/config/identity/api_key_test.go
pkg/config/identity/hmac.go
pkg/config/identity/kubernetes_auth.go
pkg/config/identity/kubernetes_auth_test.go
pkg/config/identity/mtls.go
pkg/config/identity/oauth2.go
pkg/config/identity/oauth2_test.go
pkg/config/identity/oidc.go
pkg/config/metadata.go
pkg/config/metadata/uma.go
pkg/config/metadata/uma_test.go
pkg/config/metadata/user_info.go
pkg/config/metadata/user_info_test.go
pkg/service/auth.go
pkg/service/auth_pipeline.go
pkg/service/auth_pipeline_test.go

So there is no confusion with Golang's context.

Rename AuthContext to AuthPipeline

---

controllers/secret_controller.go
controllers/secret_controller_test.go
pkg/common/auth.go
pkg/config/identity.go
pkg/config/identity/api_key.go

Since the controller cannot find secrets that have been deleted, all it has to trigger reconciliation of affected services is the namespaced name of the deleted secret. So in this case of reconciliation of delete secrets, Authorino will dig into the cache of services looking for any service whose API key identity config has cached the deleted secret as an "authorized credential". These services will be reconciled.
For the already supported cases (create secret and update secret, the only change is that service reconciliation is now triggered inside a goroutine.
----
**Verification steps:**
1. Deploy a service with API key authentication
2. Create a secret that represents a valid API key for the service deployed
3. Send requests to the API using the API key to authenticate
4. Verify that …

Reconciliation of deleted (API key) secrets

---

pkg/common/auth.go
pkg/common/auth_credentials/auth_credentials.go
pkg/common/auth_credentials/mocks/mock_auth_credentials.go
pkg/common/mocks/mock_common.go
pkg/config/config.go
pkg/config/identity.go
pkg/config/identity/api_key.go
pkg/config/identity/api_key_test.go
pkg/config/identity/hmac.go
pkg/config/identity/mtls.go
pkg/config/identity/oauth2.go
pkg/config/identity/oidc.go
pkg/config/metadata/user_info.go
pkg/service/auth.go
pkg/service/auth_pipeline.go
pkg/service/auth_test.go

Implements `401 Unauthorized` HTTP response code when all identity sources fail to evaluate the supplied credentials, instead of the currently returned status `403 Forbidden`.
The implementation complies with [RFC 7235](https://tools.ietf.org/html/rfc7235), adding as well the challenge response headers `WWW-Authenticate`. The `<type>` of each challenge is set with the key selector of the corresponding credentials config and the `realm` info to the name of the identity source. Moreover, instead of a comma-separated list of challenges inside of a single `WWW-Authenticate` header, multiple headers are added to the response (see subsection 4.1 of the RFC). E.g.:
```
< HTTP/1.1 401 Unauthorized
< www-authenticate: Bearer realm="auth-server"
< www-authenticate: APIKEY realm="friends"
```
The …

401 Unauthorized

---

docs/tutorials/showcase/README.md
examples/README.md

When trying the `Kubernetes authentication` example in `doc/examples.MD` the following line:
```
export KUBERNETES_API=$(kubectl cluster-info | head -n 1 | awk '{print $7}' | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g")
```
returned an empty output in my case:
```
msoriano@localhost:~$ export KUBERNETES_API=$(kubectl cluster-info | head -n 1 | awk '{print $7}' | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g")
msoriano@localhost:~$ echo ${KUBERNETES_API}
msoriano@localhost:~$ kubectl cluster-info | head -n 1 | awk '{print $7}' | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g"
msoriano@localhost:~$ kubectl cluster-info | head -n 1 | awk '{print $7}'
msoriano@localhost:~$ kubectl cluster-info | head -n 1
Kubernetes master is running at https://127.0.0.1:38567
```
My …

doc: Get K8S API from structured output

---

examples/README.md

When an invalid APIKey is provided an HTTP return code 401 is returned.
Execution example:
```
msoriano@localhost:~/go/src/github.com/Kuadrant/authorino (update-returned-code-doc-in-apikey-example)$ curl -H "Host: talker-api" -H "Authorization: APIKEY nono" 127.0.0.1:8000/api/test -v
*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> GET /api/test HTTP/1.1
> Host: talker-api
> User-Agent: curl/7.65.3
> Accept: */*
Handling connection for 8000
> Authorization: APIKEY nono
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< www-authenticate: APIKEY realm="friends"
< x-ext-auth-reason: the API Key provided is invalid
< date: Thu, 03 Jun 2021 09:30:57 GMT
< server: envoy
< content-length: 0
< 
* Connection #0 to host …
```

doc/examples/readme: Update documented HTTP return code for APIKey example

---

pkg/config/wristband.go
pkg/config/wristband_test.go

Some clients require the `"use": "sig"` claim to be present, to accept the key as a valid JWT signing key.

Add 'use' claim to wristband signing keys

---

Makefile
deploy/base/certmanager/issuer.yaml
deploy/base/certmanager/kustomization.yaml
deploy/base/certmanager/oidc-server-cert.yaml
deploy/base/certmanager/webhook-server-cert.yaml
deploy/base/kustomization.yaml
deploy/base/oidc_service.yaml
deploy/base/patches/oidc_server_cert_patch.yaml
docs/architecture.md
examples/README.md
examples/wristband.yaml
main.go

Serve OIDC (Wristband) HTTP endpoints over TLS

---

deploy/base/manager.yaml

This will prevent `OOMKilled` pod failure in environments with OOM killer enabled, for the current memory resources required by Authorino.
In the future, enhancements related to issues such as #23 and #24 (if followed by extracting the wristband OIDC server out of the Authorino manager pod) will allow decreasing again the request and limit for memory.

Adjust memory resource request and limit

---

Makefile
deploy/base/kustomization.yaml
deploy/base/manager.yaml
docs/deploy.md
docs/tutorials/showcase/README.md
examples/README.md

For the general case, `quay.io/3scale/authorino:latest` is now the default image that is deployed.
For the make targets `local-setup` and `local-rollout`, it will continue to build the image and push it to the local Kubernetes cluster started with Kind – now with the locally built image tagged as `authorino:local`.
This step of building an image locally can now be skept by supplying the `SKIP_LOCAL_BUILD=1` argument to the make `local-*` commands. In this case, the deployment defaults again to `AUTHORINO_IMAGE=quay.io/3scale/authorino:latest` and, just like with the more generic `make deploy`, Kubernetes will fetch the image from quay.
As usual, the `AUTHORINO_IMAGE` argument can still be used to set a different image, but it has no effect on the `local-*` make commands when …

Change default authorino image to quay.io/3scale/authorino:latest

---

Makefile

Avoids errors with the cert-manager webhook such as the ones below when applying the `Issuer` and `Certificate` resources required by Authorino, on `make local-setup`.
```
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": dial tcp 10.96.254.56:443: i/o timeout
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": dial tcp 10.96.229.147:443: connect: connection refused
```
----
Thanks to https://github.com/jetstack/cert-manager/issues/2602#issuecomment-669091541.
I …

Fix cert-manager admission web hook failure on local-setup

---

deploy/base/manager.yaml

By setting `image: quay.io/3scale/authorino:latest` inside of the `Deployment` definition, we actually removed the optional customize the image.

[hotfix] Configurable authorino image

---

controllers/secret_controller.go

After [upgrading controller-manager](https://github.com/Kuadrant/authorino/commit/e0e2b7f87c5c1be5ca382c7360214989fc8b54dc), Secrets stopped being reconciled. The issue has nothing to do with the version of controller-manager or the use of filtering predicates though, but with the implementation of the filter function that was trying to cast the value of the label to a `bool`, a solution poorly ported from [this example](https://github.com/Kuadrant/authorino/issues/116#issuecomment-875506866) without taking into account Authorino's convention of labeling secrets with `authorino.3scale.net/managed-by: authorino`, which does not translate to a truthy boolean in Golang.
In the future, we may want to change the convention and prefer a label such as `authorino.3scale.net/managed: true` …

Fix detection of authorino-managed secrets

---

deploy/overlays/cluster-wide/patches/oidc_server_cert_patch.yaml
deploy/overlays/namespaced/patches/oidc_server_cert_patch.yaml
main.go

The presence/absence of these environment variables will also be used as flag to enable/disable TLS on Authorino's built-in OIDC endpoints (instead of checking for the existence of the files). If the value set for either of the env vars points to a file in the file system that cannot be read (not found, permission issue, invalid format, etc), Authorino will fail on starting up the OIDC built-in server, instead of the old behaviour of falling back to plain HTTP. To disable TLS, make sure to NOT set these env vars (or set them to the empty string alternatively).
The `OIDC_` prefix was kept in the name of env vars to distinguish them from `TLS_CERT` and `TLS_CERT_KEY` envs, yet to be implemented for the main authorization service.
Suggested in …

Replace `OIDC_CA_PATH` env var with more explicit ones `OIDC_TLS_CERT` and `OIDC_TLS_CERT_KEY`

---

Makefile

Addresses issue #134 to replace the download of hack/setup-envtest.sh with go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest in the Makefile

Upgrade envtest

---

api/v1beta1/service_types.go
controllers/service_controller.go
install/crd/config.authorino.3scale.net_services.yaml
pkg/common/auth_credentials/auth_credentials.go
pkg/common/auth_credentials/auth_credentials_test.go

This PR removes the necessity of authentication to the external metadata server. It enables to define CRD with following metadata:
```yaml
metadata:
- name: echo-api
http:
endpoint: http://example.com/metadata
```

Generic HTTP metadata can be downloaded without any authentication

---

docs/tutorials/openshift-demo/README.md

The specific Authorino image tag used in this tutorial is tied to version of the CRD installed and therefore it must be fixed in the manifests (hosted [elsewhere](https://gist.github.com/guicassolato/4a86682282994ac5f9bb1f246f19df39)), rather than set through a parameter.

Remove `AUTHORINO_IMAGE` parameter from the OpenShift tutorial

---

pkg/common/json.go
pkg/common/json_test.go
pkg/config/response.go

Ensures directly stringified values for dynamic responses wrapped in HTTP headers, instead of using always a quoted JSON type value.
The previous use of `json.Marshal`, followed by `string(bytes)`, was causing all values responded in added HTTP headers to be wrapped between string quotes. With this change, the value of the header will be the plain stringified object – e.g. `"a string"` instead of `"\"a string\""`; `"{\"a_prop\":\"a value\"}"` instead of `"\"{\"a_prop\":\"a value\"}\""`.

common.StringifyJSON

---

examples/README.md
examples/talker-api/config.ru
examples/talker-api/talker-api-deploy.yaml

[examples/talker-api] Better logging for the Talker API

---

Makefile

Enforce repeatable builds by pinning `kustomize` and `controller-gen` tools to specific version.
The tools will be installed and used from `${PROJECT_DIR}/bin` directory. Note that if version is updated, then installed binary should be manually removed. Then the make target will install the new version.
Signed-off-by: Eguzki Astiz Lezaun <eastizle@redhat.com>

Makefile: pin controller-gen and kustomize tool versions

---

install/crd/authorino.3scale.net_authconfigs.yaml

These two OAS property descriptions were missing on #159, due to non-conflicting yet affecting changes from #167 merged first.

fixup: @base64 oas description for denyWith fields

---

api/v1beta1/auth_config_types.go
api/v1beta1/zz_generated.deepcopy.go
controllers/auth_config_controller.go
install/crd/authorino.3scale.net_authconfigs.yaml
pkg/config/metadata/generic_http.go
pkg/config/metadata/generic_http_test.go

Extends the `AuthConfig` API with option to customize the headers of the HTTP request to external sources of metadata (Generic HTTP external metadata feature).
E.g.
```yaml
spec:
metadata:
- name: external-metadata
http:
endpoint: http://external-source.io/metadata
headers:
- name: X-Requested-By
value: authorino
- name: Authorization # overwritten if used in combination with `sharedSecretRef` and `credentials.in=authorization_header`
valueFrom:
authJSON: context.request.http.headers.authorization # reuses the same authn token to authenticate with the external metadata service
```
Closes #183

Custom headers option for HTTP external metadata requests

---

api/v1beta1/auth_config_types.go
controllers/auth_config_controller.go
docs/architecture.md
examples/priorities.yaml
examples/wristband.yaml
install/crd/authorino.3scale.net_authconfigs.yaml
pkg/common/auth.go
pkg/common/mocks/mock_common.go
pkg/config/authorization.go
pkg/config/authorization/json.go
pkg/config/authorization/json_test.go
pkg/config/authorization/kubernetes_authz.go
pkg/config/authorization/kubernetes_authz_test.go
pkg/config/authorization/opa.go
pkg/config/authorization/opa_test.go
pkg/config/identity.go
pkg/config/identity_test.go
pkg/config/metadata.go
pkg/config/metadata/generic_http.go
pkg/config/metadata/generic_http_test.go
pkg/config/response.go
pkg/config/response/dynamic_json.go
pkg/config/response/dynamic_json_test.go
pkg/config/response/wristband.go
pkg/config/response/wristband_test.go
pkg/service/auth_pipeline.go
pkg/service/auth_pipeline_test.go

_Priorities_ allow to set sequence of execution for blocks of concurrent evaluators within phases of the Auth Pipeline.
Evaluators of same priority execute concurrently to each other "in a block". After syncing that block (i.e. after all evaluators of the block have returned), the next block of evaluator configs of consecutive priority is triggered.
Use cases for priorities are:
1. Saving expensive tasks to be triggered when there's a high chance of returning immediately after finishing executing a less expensive one – e.g.
- an identity config that calls an external IdP to verify a token that is rarely used, compared to verifying JWTs preferred by most users of the service;
- an authorization policy that performs some quick checks first, such as verifying allowed paths, and only if it …

Priorities for the evaluator configs

---

install/manifests.yaml
install/rbac/auth_config_editor_role.yaml
install/rbac/auth_config_viewer_role.yaml

Rename `authorino-(editor|viewer)-role` => `authorino-authconfig-(editor|viewer)-role`, so they won't collide with operator's homonimous roles associated to the `Authorino` crd.
Related to #189 and  https://github.com/Kuadrant/authorino-operator/pull/1#discussion_r750634235.

Fix name of AuthConfig editor/viewer roles

---

examples/README.md
examples/simple-oauth2.yaml
pkg/config/identity/oauth2.go
pkg/config/identity/oauth2_test.go

Makes Authorino’s OAuth2 token introspection authentication method to reject access tokens that are inactive. This was originally left to be implemented via authorization policy added to the `AuthConfig`. However, to be fully compliant with [RFC 7662](https://tools.ietf.org/html/rfc7662), inactive tokens should be rejected right in the identity verification step by default.
Start the cluster:
```sh
kind create cluster --name authorino-trial
```
Create the namespace:
```sh
kubectl create namespace authorino
```
Deploy Keycloak:
```sh
kubectl -n authorino apply -f https://raw.githubusercontent.com/kuadrant/authorino-examples/main/keycloak/keycloak-deploy.yaml
echo '127.0.0.1 keycloak' >> /etc/hosts
```
Forward local requests to the instance of Keycloak running in the cluster:
```sh
kubectl …
```

OAuth2 Token Introspection authentication rejects inactive tokens

---

pkg/common/auth_credentials/auth_credentials.go
pkg/common/auth_credentials/auth_credentials_test.go

Due to the using `strings.Split("=")` to read key-value pairs when extracting credentials from cookie headers, Authorino fails to read credentials whose values contain at least one equal sign ("="), quite common when using base64-encoded credentials with padding characters. This PR fixes the bug.

Bugfix: auth credentials in cookies should be able to contain the equal sign ('=') in the value

---

pkg/config/identity/oidc.go
pkg/config/identity/oidc_test.go

Avoid `identity.(*OIDC).verifyToken()` to `SIGSEGV` when missing the provider config:
```
panic: runtime error: invalid memory address or nil pointer dereference                                          │
[signal SIGSEGV: segmentation violation
```
Closes #182

Avoid OIDC verify token to crash when missing the provider config

---

Makefile
docs/getting-started.md
docs/user-guides/api-key-authentication.md
docs/user-guides/authenticated-rate-limiting-envoy-dynamic-metadata.md
docs/user-guides/deny-with-redirect-to-login.md
docs/user-guides/edge-authentication-architecture-festival-wristbands.md
docs/user-guides/external-metadata.md
docs/user-guides/hello-world.md
docs/user-guides/http-basic-authentication.md
docs/user-guides/injecting-data.md
docs/user-guides/json-pattern-matching-authorization.md
docs/user-guides/kubernetes-subjectaccessreview.md
docs/user-guides/kubernetes-tokenreview.md
docs/user-guides/oauth2-token-introspection.md
docs/user-guides/oidc-jwt-authentication.md
docs/user-guides/oidc-user-info.md
docs/user-guides/opa-authorization.md
docs/user-guides/passing-credentials.md
docs/user-guides/resource-level-authorization-uma.md
docs/user-guides/sharding.md
docs/user-guides/token-normalization.md

The PR changes instructions and make targets to install the Authorino Operator directly from the remote manifests, in contrast to having to clone the repo locally and run `make install deploy`.
In the same way, it changes the instructions in the Getting started page of the docs to install cert-manager and create the TLS certificates directly from the remote manifests as well, also in contrast to cloning the Authorino repo locally and running make `cert-manager`/`make certs`.

Install Authorino Operator and cert-manager from manifests

---

docs/features.md

Previously linking the feature descriptions to fixed lines of code, which are subject to change quite easily; now linking to https://pkg.go.dev/github.com/kuadrant/authorino/api/v1beta1.

[docs] Fix links to AuthConfig types

---

Makefile

Missing the tag name was causing these resources to fail to deploy locally via make targets (devs workflow).

Fix links to remote resources to deploy Keycloak, Dex, Limitador

---

README.md
docs/user-guides.md
docs/user-guides/oidc-rbac.md

Adds a user guide for a simple use case of OpenID Connect (OIDC) authentication and Role-Based Access Control (RBAC) authorization leveraging Keycloak and Authorino to protect an API.

User guide: OpenID Connect (OIDC) and Role-Based Access Control (RBAC) with Authorino and Keycloak

---

controllers/auth_config_controller.go
docs/architecture.md
install/manifests.yaml
install/rbac/k8s_auth_role.yaml
install/rbac/kustomization.yaml
install/rbac/role.yaml

Defines a new `authorino-manager-k8s-auth-role` `Role` that extracts `tokenreviews` and `subjectaccessreviews`-related permissions out of the main `authorino-manager-role` `Role`, thus allowing for this role to the bound to the Authorino SA at cluster level.
Closes #127
----
Build and deploy images of Authorino and Authorino Operator that contains the required changes:
```sh
cd $GOPATH/src/github.com/kuadrant/authorino-operator
git checkout authorino-k8s-auth-role
make docker-build OPERATOR_IMAGE=authorino-operator:local
cd $GOPATH/src/github.com/kuadrant/authorino
git checkout fix/k8s-auth-namespaced
make cluster
make cert-manager
make local-build # kind load docker-image authorino:local --name authorino
kind load docker-image authorino-operator:local --name authorino
make …
```

K8s auth ClusterRole

---

docs/features.md
docs/user-guides/kubernetes-subjectaccessreview.md
docs/user-guides/kubernetes-tokenreview.md

- Removal of the API-key id config from the example authconfig
- Removal of the use case of k8s subjectaccessreview for resource attributes from the example authconfig
...thus keeping the example focused on k8s tokenreview and subjectaccessreview for non-resource attributes permissions.
Plus:
- Use `kubectl proxy` on TokenRequest curl commands sent to the k8s API

[docs] Simplification of the k8s subjectaccessreview authz user-guide

---

api/v1beta1/auth_config_types.go
controllers/auth_config_controller.go
controllers/secret_controller.go
docs/features.md
install/crd/authorino.kuadrant.io_authconfigs.yaml
install/manifests.yaml
main.go
pkg/config/identity/api_key.go
pkg/config/identity/api_key_test.go

Adds `spec.identity.apiKey.allNamespaces: bool` to the AuthConfig API. Default value: `false` – Breaking change!
- Supported: all namespaces | same namespace of the AuthConfig (default)
- All namespaces can only be used in cluster-wide Authorino instances
Build and deploy Authorino in namespaced reconciliation/deployment mode:
```sh
make local-setup
kubectl -n authorino port-forward deployment/envoy 8000:8000 &
```
Create a couple API key secrets (different namespaces):
```sh
kubectl -n authorino apply -f -<<EOF
apiVersion: v1
kind: Secret
metadata:
name: api-key-1
labels:
authorino.kuadrant.io/managed-by: authorino
group: friends
stringData:
api_key: ndyBzreUzF4zqDQsqSPMHkRhriEOtcRx
type: Opaque
EOF
kubectl -n default apply -f -<<EOF
apiVersion: v1
kind: Secret
metadata:
name: api-key-2 …
```

Filter API keys by namespace

---

docs/architecture.md
docs/user-guides.md
docs/user-guides/host-override.md
pkg/service/auth.go
pkg/service/auth_test.go

Adds support for the "host" AuthConfig lookup key to be provided in the payload to the /Check request as Envoy ext-authz per-route "context extension".
Authorino will favor the "host" lookup key whenever passed in the context extensions before the actual "host" HTTP attribute.
This is an alternative approach for enhanced AuthConfig lookups, without changing the lookup structure too much, although relying more on Envoy to set the right payload.
This should be enough to cover use cases such as of path-based AuthConfig lookup and wildcard subdomains AuthConfig lookup.
Closes #222
Closes #171
----
In this use case, 2 different APIs are behind the same base domain and differentiated by the path prefix:
- `pets.com/dogs` →  Dogs API
- `pets.com/cats` →  Cats API
Build and deploy this branch: …

Support for "host" lookup key passed as context extension

---

pkg/service/auth.go
pkg/service/auth_test.go

Prevents Envoy Dynamic Metadata generation to break with Kubernetes API RawExtension values.
Closes #232
----
Deploy based on this branch:
```sh
make local-setup
make limitador
kubectl -n authorino port-forward deployment/envoy 8000:8000 &
```
Create the AuthConfig:
```sh
kubectl -n authorino apply -f -<<EOF
metadata:
spec:
hosts:
- talker-api-authorino.127.0.0.1.nip.io
identity:
- name: anonymous
anonymous: {}
response:
- name: rate-limit
wrapper: envoyDynamicMetadata
wrapperKey: ext_auth_data
json:
properties:
- name: username
value: john
EOF
```
Send requests:
```sh
curl http://talker-api-authorino.127.0.0.1.nip.io:8000 # 200
curl http://talker-api-authorino.127.0.0.1.nip.io:8000 # 200
curl …
```

[bugfix] Envoy Dynamic Metadata with static values

---

docs/user-guides/authenticated-rate-limiting-envoy-dynamic-metadata.md

"response status is `~409~ 429 Too Many Requests`"

Minor fix to user guide using Limitador

---

controllers/auth_config_status_updater.go
controllers/auth_config_status_updater_test.go
main.go

Makes the status updater to wait until the AuthConfig is added to the cache before marking the resource as ready.

AuthConfig status update after cache

---

api/v1beta1/auth_config_types.go
controllers/auth_config_controller.go
install/crd/authorino.kuadrant.io_authconfigs.yaml
install/manifests.yaml
pkg/auth/auth.go
pkg/evaluators/config.go
pkg/service/auth.go
pkg/service/auth_pipeline.go
pkg/service/auth_pipeline_test.go

This PR adds the possibility to add a custom message to the response body of denied requests.
closes https://github.com/Kuadrant/authorino/issues/220
1) Install and deploy an instance of authorino by running 
```
$ make local-setup
```
2) Apply an Authconfig CR
```
$ kubectl apply -n authorino -f https://raw.githubusercontent.com/kuadrant/authorino-examples/main/hello-world/authconfig.yaml
```
3) Add a denyWith policy to the Authconfig CR
```
spec:
...
denyWith:
unauthenticated:
code: 302
headers:
- name: Location
valueFrom:
authJSON: http://matrix-quotes-authorino.127.0.0.1.nip.io:8000/login.html?redirect_to={context.request.http.path}
body:
valueFrom:
authJSON: test{context.request.http.path}
```
4) Make a request against the talker API and check the response body has the custom message …

Adds custom response message body on request denial

---

pkg/json/json.go
pkg/json/json_test.go

Closes #249
Build and deploy:
```sh
make local-setup
kubectl -n authorino port-forward deployment/envoy 8000:8000 &
```
Apply te AuthConfig:
```
kubectl -n authorino apply -f -<<EOF
metadata:
spec:
hosts:
- talker-api-authorino.127.0.0.1.nip.io
denyWith:
unauthenticated:
body:
valueFrom:
authJSON: |
\{"request_path":"{context.request.http.path}"\}
headers:
- name: x-content-type
value: application/json
identity:
- apiKey:
allNamespaces: false
labelSelectors:
group: friends
credentials:
in: authorization_header
keySelector: APIKEY
name: api-clients
```
Send a request:
```sh
curl http://talker-api-authorino.127.0.0.1.nip.io:8000/hello -i
```

Fix skipping escape characters within string templates

---

.github/workflows/e2e-test.yaml

GitHub Actions already allows to pick a Git branch when dispatching manual workflows. We can use this ref for the e2e tests instead of asking for user input.

Use GHA implicit git ref instead of user input in the e2e test workflow

---

tests/authconfig.yaml
tests/e2e-test.sh

Adds evaluator caching config to the e2e tests.
- Identity > OAuth2 token introspection
- Metadata > Generic HTTP (request to IP location service)
- Metadata > OIDC UserInfo
- Metadata > UMA

[e2e] Evaluator caching

---

go.mod

So we are consistent with the Golang version required to build the project and get deeper insights of indirect dependencies.

go.mod for v1.17

---

.gitignore
go.mod
go.sum
pkg/evaluators/identity/kubernetes_auth.go
pkg/evaluators/response/wristband.go

[dgrijalva/jwt-go](https://github.com/dgrijalva/jwt-go) has no longer been maintained for a while and v3.2.0 is known to have [security vulnerabilities](https://snyk.io/vuln/golang:github.com%2Fdgrijalva%2Fjwt-go?utm_medium=Partner&utm_source=RedHat&utm_campaign=Code-Ready-Analytics-2020&utm_content=vuln/golang:github.com%2Fdgrijalva%2Fjwt-go) only addressed on v4, which unfortunately seems to have abandoned.
Meanwhile, a clone has been maintained by the community, i.e. [golang-jwt/jwt](https://github.com/golang-jwt/jwt), where the aforementioned vulnerabilities have been fixed.
Dependency Analytics Report after this change:

Replace dgrijalva/jwt-go with golang-jwt/jwt

---

.gitignore
controllers/auth_config_controller_test.go

This will prevent a false-positive on static code analysis pointing to vulnerabilities such as CVE-2006-5901 and CVE-2005-3725, and it is completely unneeded for testing the AuthConfig controller.

Avoid static IP addresses in the tests

---

main.go
pkg/evaluators/authorization/opa.go
pkg/service/oidc.go

Replace all usage of the MD5 algorithm with SHA-256:
- Tracing logs of the OIDC server (`request id`)
- Precompiled OPA policies
- Leader election secrets
Although neither of the above raises security concerns due to not being used for storing hashed sensitive data, but since MD5 algorithm may be disabled altogether in specific deployments, at the level of the operating system, and as a good practice in general, those applications of this algorithms by Authorino should be replaced to rely on at least SHA-1 instead.
Closes #269
```sh
kubectl -n authorino patch --type=json deployment/authorino --patch '[{"op":"replace","path":"/spec/template/spec/containers/0/args","value":["--enable-leader-election"]}]'
kubectl -n authorino wait --timeout=300s …
```

Replace MD5 usage with SHA-256

---

controllers/auth_config_controller.go
controllers/auth_config_controller_test.go

Default to Anonymous access whenever the AuthConfig does not include any identity verification policies.
This will simplify writing AuthConfig for authorization only.
Closes #268 
```sh
kubectl -n authorino port-forward deployment/envoy 8000:8000 &
```
```sh
kubectl -n authorino apply -f -<<EOF
metadata:
spec:
hosts:
- talker-api-authorino.127.0.0.1.nip.io
EOF
```
```sh
curl http://talker-api-authorino.127.0.0.1.nip.io -i
```

Default to Anonymous access

---

.github/workflows/build-images.yaml

Using 'platforms' option of redhat-actions/buildah-build instead of 'archs'

[hotfix] Multi-Platform auto build (3)

---

.github/workflows/build-images.yaml
Dockerfile

This is yet another attempt to make multi-platform build to work with buildah.
Following the example provided by [redhat-actions/buildah-build](https://github.com/redhat-actions/buildah-build/blob/main/.github/workflows/multiarch.yml), we are giving a try with enabling qemu in the environment while again letting for Golang to auto-detect the platform.
In the same PR, we're adding `workflow_dispatch` to the triggers.

[hotfix] Multi-Platform auto build (4)

---

.github/workflows/build-images.yaml

This is for the workflow_dispatch trigger only, as builds triggered automatically on pushes to the main branch will be tagged 'latest' by default.

[GHA] Tag container images with branch/tag name

---

.github/workflows/integration-test.yaml

Part 3/3 of #236.
---
- Triggers after the 'Build and push image' workflow is successfully completed.
- Sets up a cluster and builds Authorino based on the freshly built image (pulled from public registry)
- Does not require cloning the repo - applies all resources defining inline in the steps or from remote manifests

[GHA] Smoke Tests

---

tests/e2e-test.sh

Fix Authorino pod not ready before start port-forwarding requests to the OIDC Festival Wristband service.
Avoids, e.g.:

[e2e] Fix Authorino pod not ready

---

Makefile

Modifies the Makefile so it is possible to deploy locally (dev env) to a pre-existing Kuberentes namespace (e.g. default).
```sh
make local-setup NAMESPACE=default FF=1
```
Command above should NOT fail with:
```
Error from server (AlreadyExists): namespaces "default" already exists
```

Local deploy to pre-existing namespace

---

docs/user-guides.md
docs/user-guides/validating-webhook.md

Adds a new user guide of how to use Authorino as a generic Kubernetes ValidatingWebhook service where the rules to validate a request to the Kubernetes API are written in an AuthConfig.
Depends on [Kuadrant/authorino-operator#61](https://github.com/Kuadrant/authorino-operator/pull/61).

User guide: Using Authorino as ValidatingWebhook service

---

pkg/service/auth.go
pkg/service/auth_test.go

- Method (either `GET` or `POST`)
- Headers
- Path (fixed: `/check`)
- Host
- Scheme
- Query
- Fragment
- Protocol

HTTP request attributes passed in the call for the raw HTTP authorization check

---

Makefile

To prevent `make deploy` of raising a permission error when the `EDITOR` env var is not set.

[makefile] Default EDITOR set to vi if undefined

---

controllers/auth_config_controller.go
controllers/auth_config_controller_test.go

Ensures all valid hosts are added to the cache despite presence of invalid (taken) ones among them.
Closes #323
```sh
make local-setup # clusterWide: true
kubectl create namespace user-1
kubectl -n user-1 apply -f -<<EOF
metadata:
name: auth-1
namespace: user-1
spec:
hosts:
- talker-api.127.0.0.1.nip.io
response:
- name: x-auth-data
json:
properties:
- name: authconfig
value: auth-1
EOF
kubectl create namespace user-2
kubectl -n user-2 apply -f -<<EOF
metadata:
name: auth-2
namespace: user-2
spec:
hosts:
- talker-api.127.0.0.1.nip.io
- talker-api.io
response:
- name: x-auth-data
json:
properties:
- name: authconfig
value: auth-2
EOF
kubectl port-forward deployment/envoy …
```

All valid hosts added to cache

---

deploy/authorino.yaml

Updates the template file for creating the Authorino CR on local deployments.
Makes sure all fields of the CRD (as of today) are in the template, with values set to their corresponding defaults.

Update template of the Authorino CR

---

main.go
pkg/service/auth.go
pkg/service/auth_test.go

Closes https://github.com/Kuadrant/authorino/issues/298
This PR introduces a way to limit the request body size of Authorino "HTTP external authorization", thus preventing clients from accidentally or maliciously sending a large request and wasting server resources.
* Configured by env `MAX_REQUEST_BYTES`
* Defaults to 8192 (8KB)
* When the payload is larger, it returns an HTTP `413`

Protection against large payloads

---

controllers/auth_config_controller.go
controllers/auth_config_controller_test.go
pkg/cache/cache.go
pkg/cache/mocks/mock_cache.go

Delete all entries in the cache related to an AuthConfig before adding again only to hosts that apply.
Ensures hosts occasionally removed from the AuthConfig on an update are no longer linked to the AuthConfig in the cache after the reconciliation.
Closes #326.
Build, deploy, setup:
```sh
make local-setup
kubectl port-forward deployment/envoy 8000:8000 &
```
Create an AuthConfig for 2 hosts:
```sh
kubectl apply -f -<<EOF
metadata:
spec:
hosts: ["host-1", "host-2"]
EOF
```
Send requests to the hosts:
```sh
curl -H 'Host: host-1' http://localhost:8000 -i
```
```sh
curl -H 'Host: host-2' http://localhost:8000 -i
```
Remove one of the hosts from the AuthConfig:
```sh
kubectl apply -f -<<EOF
apiVersion: …
```

Fix phantom host association

---

Dockerfile

Changes container base image to Red Hat UBI 8 images.
- **Builder:** [registry.access.redhat.com/ubi8/go-toolset:1.17.10](https://catalog.redhat.com/software/containers/ubi8/go-toolset/5ce8713aac3db925c03774d1?tag=1.17.10)
- **Runtime:** [registry.access.redhat.com/ubi8/ubi-minimal:latest](https://catalog.redhat.com/software/containers/ubi8-minimal/5c64772edd19c77a158ea216?tag=latest)
As a side effect, image size will grow from ~25-27 MB to ~59-63 MB (depending on the platform – linux/arm64 or linux/amd64, respectively).
On the good side, automated security scans in Quay.io will work (closes #310).

Red Hat Universal Base Image (UBI) 8

---

Makefile

Fixes the following error thrown when running the tests in the darwin/arm64 platform:
```
unable to fetch checksum for requested version: unable fetch metadata for kubebuilder-tools-1.21.2-darwin-arm64.tar.gz -- got status "404 Not Found" from GCS
```
This is okay because in the end we only build for linux OS anyway.
**Additional note to reviewers:**
We are not really using [controller-runtime/pkg/envtest](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/envtest) in Authorino since the removal of `controllers/suite_test.go` (#274). We could remove the target that installs setup-envtest and refs in the Makefile altogether. However, in the spirit of aiming in the near future to standardise how integration tests are implemented across components and perhaps get the default suite_test.go …

Fix os parameter for setting up for integration tests

---

controllers/auth_config_controller.go

- resource name printed to the logs in the format `<namespace>/<name>`
- number  of resources (`count`) printed to the logs
E.g.:
```jsonc
{"level":"info","ts":1659351123.8340561,"logger":"authorino.controller-runtime.manager.controller.authconfig.bootstrap","msg":"building cache index","count":4}
{"level":"debug","ts":1659351123.8347695,"logger":"authorino.controller-runtime.manager.controller.authconfig.bootstrap","msg":"building cache index","authconfig":"user-1/auth-1"}
{"level":"debug","ts":1659351123.834799,"logger":"authorino.controller-runtime.manager.controller.authconfig.bootstrap","msg":"building cache index","authconfig":"user-2/auth-2"}
{"level":"debug","ts":1659351123.8348057,"logger":"authorino.controller-runtime.manager.controller.authconfig.bootstrap","msg":"building …
```

Fix bootstrap index debug log message

---

controllers/auth_config_controller.go
controllers/auth_config_controller_test.go

AuthConfig controller enhancements

---

controllers/auth_config_controller.go
controllers/auth_config_controller_test.go
docs/architecture.md
docs/user-guides/logging.md

Unifies the two traditional behaviours for `namespaced` reconciliation mode and for `cluster-wide` reconciliation mode regarding how a host is considered to be taken or not into one single behaviour. I.e., the namespace that the AuthConfigs belong to no longer matters; if a host is taken by an AuthConfig, it cannot be linked to another one.
Users who want to link a host to a different AuthConfig will first need to remove the host from the existing AuthConfig linked to the host and then add the new one. In the case of specific hosts vs. wildcard hosts, the more specific ones will always have to be linked before and then the more generic ones.
----
Contains commits of #339 and #342

Reject linking AuthConfigs to hosts already taken regardless of namespace

---

.github/workflows/build-images.yaml
Dockerfile
Makefile
docs/user-guides/logging.md
main.go

The Authorino version info can be specified as a build argument (`VERSION`) of the `docker build` command, which is then set as an ldflag in the `go build` command.
When using the Makefile:
1. If `VERSION` is not specified, it defaults to the Git ref (SHA-1) of HEAD;
2. The image tag (`IMAGE_TAG`) is inferred from the value of `VERSION` (user-defined or set to default):
- When it matches `^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$` (e.g. '0.10.0-pre'), the tag is set to `v$VERSION` (e.g. 'v0.10.0-pre');
- otherwise, the tag is set to fixed value 'local'.
Additionally, a new parameter `IMAGE_REPO` was introduced to the Makefile (default: 'authorino'), and the existing parameter `AUTHORINO_IMAGE` now defaults to `$(IMAGE_REPO):$(IMAGE_TAG)`.
In CI, `VERSION` is inferred based on `GITHUB_REF_NAME`:
- …

Embed the Authorino version info into the binary

---

pkg/evaluators/authorization/opa.go
pkg/evaluators/authorization/opa_test.go

Bugfix: avoid panic when external OPA response misses Content-Type header

---

controllers/status_report.go
pkg/evaluators/authorization/opa.go
pkg/evaluators/identity/api_key.go
pkg/evaluators/identity/mtls.go

Apart from a good practice in general whenever multiple concurrent reads and writes are expected, this will fix the following race condition error related with the status update of the AuthConfigs:
```
concurrent map read and map write
goroutine 734 [running]:
runtime.throw({0x1cad2f9, 0xc0030e6ae0})
/usr/lib/golang/src/runtime/panic.go:1198 +0x71 fp=0xc0005d5950 sp=0xc0005d5920 pc=0x436eb1
runtime.mapaccess2_faststr(0x1f4e7a8, 0xc0030e6bd0, {0xc0005d5bf0, 0x1c})
/usr/lib/golang/src/runtime/map_faststr.go:116 +0x3d4 fp=0xc0005d59b8 sp=0xc0005d5950 pc=0x412c34
github.com/kuadrant/authorino/controllers.(*StatusReportMap).Get(...)
/workspace/controllers/status_report.go:20
github.com/kuadrant/authorino/controllers.(*AuthConfigStatusUpdater).updateAuthConfigStatus(0xc00061e700, {0x1f4e7a8, …
```

Use RWMutex

---

controllers/auth_config_controller.go
controllers/auth_config_controller_test.go

The AuthConfig reconciler, when bootstrapping the index of AuthConfigs, was not taking the label selectors into account when selecting the list of resources to reconcile, causing hosts out os scope to the added to the index. This changes makes sure the label selectors are used when selecting the resources.

[Bugfix] Only bootstrap AuthConfigs in scope

---

pkg/service/auth_pipeline.go
pkg/service/auth_pipeline_test.go

Fixes concurrent read/write access to the maps of the Auth Pipeline that store identity, metadata, authorization and response objects per config/evaluator, thus avoiding fatal errors, e.g., when writing evaluated objects to the map whil at the same time requesting Authorization JSON and/or resolved identity object.
Closes #356

Safe concurrent access to the Auth Pipeline maps

---

Dockerfile

Back to building the  container image based on ubi9/go-toolset now that [ubi9/go-toolset:1.18](https://catalog.redhat.com/software/containers/ubi9/go-toolset) is available.

Build the container image based on ubi9/go-toolset

---

controllers/auth_config_controller.go
controllers/status_report.go
main.go
pkg/health/health.go
pkg/health/health_test.go
pkg/utils/utils.go
pkg/utils/utils_test.go

Implements health and readiness probe endpoints for the controllers. ATM, the endpoints are trivial readiness and health check endpoints the by default always return "ok".
The aggregated status of all AuthConfigs watched by the controller is an opt-in check.
New endpoints introduced:
- `/healthy`: Health probe (ping)
- `/readyz`: Aggregated readiness probe (by default, none)
- `/readyz/authconfigs`: Aggregated status of all AuthConfigs watched by the controller
In general, all endpoints return either `200` ("ok") or `500` (when 1+ probes fail).
The default binding network address is `:8081`. It can be changed using a newly introduced flag (command-line arg) `--health-probe-addr`.
The following query string parameters are supported:
- `verbose=any`: more verbose response messages;
- …

Readiness probe

---

Makefile
README.md
pkg/evaluators/authorization/json_test.go

- fixes benchstat command for the latest (entirely new) version
- increases the number of runs to 10, for better quality sample statistics
- modifies the JSON pattern-matching authz benchmark to match perfectly the use case of the OPA authz benchmark, for comparison
- updates the latest benchmarks in the README

[GHA] fix unit benchmarks

---

api/v1beta1/auth_config_types.go
docs/features.md
install/crd/authorino.kuadrant.io_authconfigs.yaml
install/manifests.yaml
pkg/json/json.go
pkg/json/json_test.go

This adds a function to strip out non printable Unicode characters returned in the authorization json. See issue #373.

Add function to remove non printable characters

---

controllers/auth_config_controller.go

hotfix: http metadata and callbacks should not fail when missing creds config

---

main.go

Add [gRPC server reflection](https://github.com/grpc/grpc-go/blob/master/Documentation/server-reflection-tutorial.md#enable-server-reflection).
Requires:
- [gRPCurl](https://github.com/fullstorydev/grpcurl)
Build and run:
```sh
make cluster install build
bin/authorino server
```
In a separate shell:
```sh
grpcurl -plaintext localhost:50051 list
```
```sh
grpcurl -plaintext localhost:50051 list envoy.service.auth.v3.Authorization
```
```sh
grpcurl -plaintext localhost:50051 describe envoy.service.auth.v3.Authorization
```
```sh
grpcurl -plaintext localhost:50051 describe envoy.service.auth.v3.CheckRequest
```

gRPC server reflection

---

pkg/evaluators/authorization/opa.go
pkg/evaluators/identity/oauth2.go
pkg/evaluators/metadata/generic_http.go
pkg/evaluators/metadata/uma.go
pkg/evaluators/metadata/user_info.go

Fixes #385 
cc @guicassolato 
Verification steps courtesy @guicassolato :
Step 1: Initialize cluster
```
make cluster install build
```
Step 2: Bring up authorino
```
bin/authorino server --tracing-service-endpoint http://localhost:14268/api/traces
```
Step 3: Apply auth-config
```
metadata:
spec:
hosts:
- talker-api-authorino.127.0.0.1.nip.io
metadata:
- name: echo
http:
endpoint: https://echo-api.3scale.net/
response:
- name: echo
json:
properties:
- name: response
valueFrom:
authJSON: auth.metadata.echo
```
Step 4: Sending an external authorization request to a gRPC server using `grpcurl`
```
for repo in \
envoyproxy/data-plane-api \
googleapis/googleapis \
envoyproxy/protoc-gen-validate \
cncf/udpa …
```

WIP: Add propagation to external services

---

install/crd/patches/oneof_in_authconfigs.yaml
install/manifests.yaml
tests/authconfig-invalid.yaml
tests/e2e-test.sh

Reported at https://github.com/Kuadrant/authorino/pull/393#discussion_r1202653273

fix: API one-of constraints

---

Dockerfile

Adds new dedicated home path in the FS within the container for the binary and any other future Authorino files. The directory is owned by a new `authorino` Linux user and `root` Linux group.
This allows running Authorino on OpenShift with the default unprivileged user on standard `restricted` security context strategy, without the files having to be owned by root. As for other environments, users can choose to run the container as root or as the less privileged `authorino` user.
Implements **OPTION 4** proposed for [kuadrant/limitador](https://github.com/kuadrant/limitador) in https://github.com/Kuadrant/limitador/issues/175#issuecomment-1542578528.

Tighten up the permissions over Authorino files within the container

---

.github/workflows/integration-test.yaml
tests/e2e-test.sh

Fixes missing ref to the invalid AuthConfig file in the env settings for the Smoke tests workflow.

[gha] fix: smoke tests

---

docs/features.md
pkg/json/json.go
pkg/json/json_test.go

Automatically escaping of double quotes within strings extracted from the Authorization JSON and decoded with the `@base64` custom modifier.
**Description of the problem:**
Values decoded using the `@base64` custom modifier for JSON paths can be truncated due to the presence of unescaped double quotes in the string.
This also causes the conversion of values to other JSON types (e.g. objects and arrays) using the built-in `@fromstr` modifier to fail if the value contains unescaped double quotes. Users have to explicitly escape the double quotes in the source before encoding the string, which is not always possible, such as in the case of stringified JSON baggage automatically injected.
**Use case:**
To be able to parse base64 encoded strings that represent valid JSON types other than …

fix: Escape base64-decoded strings

---

docs/features.md
pkg/evaluators/identity/kubernetes_auth.go
pkg/evaluators/identity/kubernetes_auth_test.go

Makes the Kubernetes TokenReview-based identity method to always fill the identity object from the [status](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-review-v1/#TokenReviewStatus) field of the TokenReview response, as opposed to the current hybrid behaviour of trying to detect whether the verified access token is a JWT or an opaque token.
Closes #394.
---
**_Warning!_** This is a breaking change and users of Authorino Kubernetes identity verification method must consider its impact to existing AuthConfigs before upgrading to a new version.
Users relying on JWT detection can still extract, decode and parse the JWT directly from the Authorization header. Here’s an example extending the identity object<sup>*</sup>:
```yaml
spec:
identity:
- name: …
```

feat: Simple Kubernetes TokenReview identity object

---

docs/user-guides/observability.md

```
auth_server_authconfig_duration_seconds_bucket{authconfig="test",namespace="test-ns",le="0.001"} 0
auth_server_authconfig_duration_seconds_bucket{authconfig="test",namespace="test-ns",le="0.051000000000000004"} 1
auth_server_authconfig_duration_seconds_bucket{authconfig="test",namespace="test-ns",le="0.101"} 1
auth_server_authconfig_duration_seconds_bucket{authconfig="test",namespace="test-ns",le="0.15100000000000002"} 1
auth_server_authconfig_duration_seconds_bucket{authconfig="test",namespace="test-ns",le="0.201"} 1
auth_server_authconfig_duration_seconds_bucket{authconfig="test",namespace="test-ns",le="0.251"} 1
```

Fix documentation wrong metric type

---

.github/workflows/integration-test.yaml
Makefile

* Bump kind to v0.20.0
* Use downloaded kind binary in kind commands

kind: bump to v0.20.0 & use bin/kind binary for makefile commands

---

.github/workflows/build-images.yaml
.github/workflows/code-style.yaml
.github/workflows/e2e-test.yaml
.github/workflows/go-test.yaml
.github/workflows/integration-test.yaml

Update workflow actions

---

controllers/auth_config_status_updater_test.go
pkg/auth/credentials.go
pkg/auth/credentials_test.go
pkg/evaluators/authorization/kubernetes_authz.go
pkg/evaluators/authorization/kubernetes_authz_test.go
pkg/evaluators/authorization/opa.go
pkg/evaluators/identity/hmac.go
pkg/evaluators/identity/kubernetes_auth.go
pkg/evaluators/identity/kubernetes_auth_test.go
pkg/evaluators/identity/plain.go
pkg/evaluators/identity/plain_test.go
pkg/evaluators/metadata/user_info.go
pkg/evaluators/metadata/user_info_test.go
pkg/json/json.go
pkg/service/auth.go
pkg/service/health.go
pkg/service/oidc.go

Various lint issues corrected as found by staticcheck including duplicate imports, deprecated imports and others ([ST1017](https://staticcheck.dev/docs/checks/#ST1017), [S1007](https://staticcheck.dev/docs/checks/#S1007), [ST1006](https://staticcheck.dev/docs/checks/#ST1006), [ST1005](https://staticcheck.dev/docs/checks/#ST1005), [ST1012](https://staticcheck.dev/docs/checks/#ST1012)).

Fix various lint issues

---

README.md
docs/contributing.md

Point people interested to reach out to the [#kuadrant](https://kubernetes.slack.com/archives/C05J0D0V525) channel in the Kubernetes Slack workspace.

#kuadrant channel on kubernetes.slack.com

---

controllers/auth_config_controller.go
docs/user-guides/sharding.md

Follow the [user-guide](https://github.com/Kuadrant/authorino/blob/main/docs/user-guides/sharding.md) up to step 9. to verify that there are no logs present when adding the disabled label.
Remove the disabled label from the `AuthConfig`:
```
kubectl -n myapp label authconfig/auth-config-2 disabled-
```
Update the authorino-production deployment to use an image built from this branch:
```
kubectl patch authorino/authorino-production --type=merge -p '{"spec":{"image":"quay.io/acatterm/authorino:log-deindex"}}'
kubectl rollout restart deployment authorino-production
```
Watch the logs:
```
kubectl logs -f $(kubectl get pods -l authorino-resource=authorino-production -o name)
```
Re-label the `AuthConfig` as disabled:
```
kubectl -n myapp label authconfig/auth-config-2 disabled=true
```
See a …

Add log for when authconfig is de-indexed

---

api/v1beta2/auth_config_conversion.go
api/v1beta2/auth_config_conversion_test.go

Fix back and forth conversion of [`runtime.RawExtension`](https://pkg.go.dev/k8s.io/apimachinery@v0.23.0/pkg/runtime#RawExtension) fields.
Example of fields and values affected:
- Extended properties of identity objects (new `defaults` and `overrides` of the authentication configs)
- Custom `headers` of the former `denyWith` spec (new `response.(unauthenticated|unauthorized).headers`)
- Custom `message` and `body` of the former `denyWith` spec, as well as all other fields typed in v1beta1 as [`StaticOrDynamicValue`](https://pkg.go.dev/github.com/kuadrant/authorino/api/v1beta1#StaticOrDynamicValue), when the field was set to a static string value containing line breaks or any other character that requires escaping when marshalled
Closes #430.
```sh
```
```sh
kubectl …
```

fix: conversion of raw extension fields

---

install/crd/patches/oneof_in_authconfigs.yaml
install/manifests.yaml

Add missing top-level `when` conditions one-of constraints. Should have been in https://github.com/Kuadrant/authorino/pull/427.
① Setup:
```sh
```
② Create an AuthConfig otherwise invalid
```sh
kubectl apply -f -<<EOF
apiVersion: authorino.kuadrant.io/v1beta2
metadata:
name: toystore
spec:
hosts:
- api.toystore.com
when:
- any:
- any:
- all:
- operator: eq
selector: context.request.http.method
value: GET
- operator: matches
selector: context.request.http.path.@extract:{"sep":"?"}
value: /cars.*
- all:
- operator: eq
selector: context.request.http.method
value: GET
- operator: matches
selector: context.request.http.path.@extract:{"sep":"?"}
value: /dolls.*
- any:
- all:
- operator: matches
selector: context.request.http.path.@extract:{"sep":"?"} …
```

fix: missing one-of constraint of top-level when conditions

---

api/v1beta2/auth_config_conversion_test.go
pkg/evaluators/identity/oidc_test.go

Popped up more often after #435.

fix: flaky tests

---

README.md
docs/contributing.md
docs/getting-started.md
docs/user-guides/anonymous-access.md
docs/user-guides/api-key-authentication.md
docs/user-guides/authenticated-rate-limiting-envoy-dynamic-metadata.md
docs/user-guides/authzed.md
docs/user-guides/caching.md
docs/user-guides/deny-with-redirect-to-login.md
docs/user-guides/edge-authentication-architecture-festival-wristbands.md
docs/user-guides/envoy-jwt-authn-and-authorino.md
docs/user-guides/external-metadata.md
docs/user-guides/http-basic-authentication.md
docs/user-guides/injecting-data.md
docs/user-guides/json-pattern-matching-authorization.md
docs/user-guides/keycloak-authorization-services.md
docs/user-guides/kubernetes-subjectaccessreview.md
docs/user-guides/kubernetes-tokenreview.md
docs/user-guides/mtls-authentication.md
docs/user-guides/oauth2-token-introspection.md
docs/user-guides/observability.md
docs/user-guides/oidc-jwt-authentication.md
docs/user-guides/oidc-rbac.md
docs/user-guides/oidc-user-info.md
docs/user-guides/opa-authorization.md
docs/user-guides/passing-credentials.md
docs/user-guides/resource-level-authorization-uma.md
docs/user-guides/sharding.md
docs/user-guides/token-normalization.md
docs/user-guides/validating-webhook.md

Related to https://github.com/Kuadrant/docs.kuadrant.io/pull/40

Markdown in HTML blocks

---

pkg/trace/exporter.go

Fixes an error in the initialization of Authorino when tracing services are enabled.
Error message:
```
cannot merge resource due to conflicting Schema URL
```
Stacktrace:
```
main.setupTelemetryServices
/usr/src/authorino/main.go:409
main.setup
/usr/src/authorino/main.go:387
main.runAuthorizationServer
/usr/src/authorino/main.go:225
github.com/spf13/cobra.(*Command).execute
/opt/app-root/src/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944
github.com/spf13/cobra.(*Command).ExecuteC
/opt/app-root/src/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
/opt/app-root/src/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext
/opt/app-root/src/go/pkg/mod/github.com/spf13/cobra@v1.7.0/comman …
```

fix: bump OpenTelemetry Schema URL to 1.21.0

---

docs/architecture.md
docs/contributing.md
docs/user-guides/deny-with-redirect-to-login.md

Ref: https://github.com/Kuadrant/docs.kuadrant.io/issues/56

[docs] Fixing some broken links

---

RELEASE.md

This is part of https://github.com/Kuadrant/architecture/pull/46, after [this comment](https://github.com/Kuadrant/architecture/pull/46#discussion_r1495657625).

HowTo release Authorino

---

docs/features.md
docs/user-guides/mtls-authentication.md
pkg/evaluators/identity/mtls.go
pkg/evaluators/identity/mtls_test.go

Make the mTLS identity verification method to check for 'Client authentication' extended key usage, instead of default 'Server authentication' ([ref](https://access.redhat.com/documentation/en-us/red_hat_certificate_system/9/html/administration_guide/standard_x.509_v3_certificate_extensions#Standard_X.509_v3_Certificate_Extensions-extKeyUsage)).

Check 'client auth' key usage on mtls identity

---

main.go

Options for the extra metrics handler of the controller manager need to be set before creating the manager.
Otherwise, the `/server-metrics` endpoint will not be included and return a 404.
```sh
kubectl port-forward service/authorino-controller-metrics 8080:8080 2>&1 >/dev/null &
curl http://localhost:8080/server-metrics
```
You should see the server metrics and not a `404 Not Found`.

fix: extra metrics handler

---

Makefile
pkg/service/auth.go
pkg/service/auth_test.go

Improved handler for invalid ext_authz requests errors.
```sh
make cluster install run
```
In a separate shell: (Requires [grpcurl](https://github.com/fullstorydev/grpcurl))
```sh
grpcurl -plaintext -d @ localhost:50051 envoy.service.auth.v3.Authorization.Check <<EOF
{}
EOF
```
**Before:**
Authorino panics.
**After:**
Authorino handles the error nicely and the returns the following response:
```
{
"status": {
"code": 3
},
"deniedResponse": {
"status": {
"code": "BadRequest"
},
"headers": [
{
"header": {
"key": "X-Ext-Auth-Reason",
"value": "Invalid request"
}
}
]
}
}
```

Handle invalid ext_authz request

---

docs/user-guides/mtls-authentication.md
pkg/evaluators/identity/mtls_test.go

Generate 4096-bit cert keys and use sha512 algorithms for certificate requests in the `openssl` examples in the docs and mtls test cases, to avoid false-positive security flagging.

[docs] avoid false positive openssl-related security flagging

---

.github/workflows/integration-test.yaml

Related  https://github.com/Kuadrant/authorino-operator/pull/218
Missed updating to use v1beta3 of AuthConfig in smoke tests in the initial introduction of v1beta3 in https://github.com/Kuadrant/authorino/pull/493

fixup: use v1beta3 for smoke tests

---

pkg/evaluators/authorization/authzed.go
pkg/evaluators/authorization/kubernetes_authz.go
pkg/evaluators/metadata/generic_http.go
pkg/json/json.go

Fixes conversion of `ValueOrSelector.Value` (based on [`runtime.RawExtension`](https://pkg.go.dev/k8s.io/apimachinery@v0.28.3/pkg/runtime#RawExtension)) to string, used at the following configs:
- SubjectAccessReview authorization
- External HTTP requests (metadata, external Rego policies, etc)
- SpiceDB check permissions
This bug was introduced in [v0.18.0](https://github.com/Kuadrant/authorino/releases/tag/v0.18.0), when the AuthConfig controller was updated to work with `v1beta2` type (previously (`v1beta1`), thus activating the option to set static values to JSON/YAML types other than strings. The conversion functions used in the features listed above were overlooked in the process and remain naively treating static values (stored in Golang `interface{}` variables) as if they were …

fix: RawExtension to string conversion

---

pkg/evaluators/authorization/authzed.go
pkg/evaluators/authorization/kubernetes_authz.go
pkg/evaluators/metadata/generic_http.go
pkg/json/json.go

patch: RawExtension to string conversion (v0.18)

---

README.md
docs/getting-started.md
docs/user-guides/anonymous-access.md
docs/user-guides/api-key-authentication.md
docs/user-guides/authenticated-rate-limiting-envoy-dynamic-metadata.md
docs/user-guides/authzed.md
docs/user-guides/caching.md
docs/user-guides/deny-with-redirect-to-login.md
docs/user-guides/edge-authentication-architecture-festival-wristbands.md
docs/user-guides/envoy-jwt-authn-and-authorino.md
docs/user-guides/external-metadata.md
docs/user-guides/hello-world.md
docs/user-guides/http-basic-authentication.md
docs/user-guides/injecting-data.md
docs/user-guides/json-pattern-matching-authorization.md
docs/user-guides/keycloak-authorization-services.md
docs/user-guides/kubernetes-subjectaccessreview.md
docs/user-guides/kubernetes-tokenreview.md
docs/user-guides/mtls-authentication.md
docs/user-guides/oauth2-token-introspection.md
docs/user-guides/oidc-jwt-authentication.md
docs/user-guides/oidc-rbac.md
docs/user-guides/oidc-user-info.md
docs/user-guides/opa-authorization.md
docs/user-guides/passing-credentials.md
docs/user-guides/resource-level-authorization-uma.md
docs/user-guides/sharding.md
docs/user-guides/token-normalization.md
docs/user-guides/validating-webhook.md

- Adding latest as the version to docs links
- update `kuadrant-operator/doc/auth` to `kuadrant-operator/doc/overviews/auth` as the old link wasn't valid anymore.

add version and fix broken link

---

install/crd/kustomization.yaml

Kustomize `patchesJson6902` is deprecated in favour of `patches` as runnng `make manifests` previously had the following warning:
* Passing CI jobs
* Running `make manifests` should no longer display the above warning

kustomize: use patches instead of patchesJson6902

---

.github/workflows/code-style.yaml
.github/workflows/e2e-test.yaml
.github/workflows/go-test.yaml
.github/workflows/smoke-test.yaml
Dockerfile
docs/contributing.md
go.mod

This also fixes [CVE-2025-22866](https://access.redhat.com/security/cve/CVE-2025-22866) (ppc64le arch)

Upgrade Go version to 1.22

---

go.mod

Same as https://github.com/Kuadrant/authorino-operator/pull/249

Explicitly state Z stream go version in go.mod, version set to 1.22.5

---

Makefile

* Refactor makefile dependency tools using [Kubebuilder v4 project makefile as template](https://github.com/kubernetes-sigs/kubebuilder/blob/012e741d07a34da23451b9d0c946f89dddd43609/testdata/project-v4/Makefile#L168-L232)
* Bind tool version to "X-V_BINARY" that will be checked instead by `make`. This will ensure that should the version of the tool is changed/updated, `make` will download this new version and update the symlink
* Minor consistency update to download uber mockgen which was missed when mockgen was changed as part of https://github.com/Kuadrant/authorino/pull/536
* Passing github workflow
* Test tool binary is downloaded if version has changed
```
make kind
./bin/kind version
KIND_VERSION=v0.23.0 make kind
./bin/kind version
```

makefile: refactor dependency tooling install

---

pkg/evaluators/identity.go

[e2e is failing](https://github.com/Kuadrant/authorino/actions/runs/15439930133/job/43455108934) with the error:
```sh
clusterrolebinding.rbac.authorization.k8s.io/talker-api-admins created
waiting authconfig ready. condition met
sending multiple requests
Test failed [#1]:
GET   http://talker-api.127.0.0.1.nip.io:8000/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6InFxSE9fa0NHWmdNZEZ0ZXJTSFFucURlbml2Z29aSGlNR2hkTll3WnJmNU0ifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzQ5MTI3NjkxLCJpYXQiOjE3NDkxMjcwOTEsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJhdXRob3Jpbm8iLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiYXBwLTEtc2EiLCJ1aWQiOiI3YTgxYjNlNC0wMzE4LTQwMGUtODA2NC0xYmI1Y2IyYjJlZjIifX0sIm5iZiI6MT …
```

fix: nil pointer from typed nil of auth.OpenIdConfigStore for UserInfo

---

.github/workflows/code-style.yaml
.github/workflows/e2e-test.yaml
.github/workflows/go-test.yaml
.github/workflows/smoke-test.yaml

Closes: https://github.com/Kuadrant/authorino/issues/549
Uses go version from `go.mod` where possible
- Passing github actions

gha: use go version from go.mod

---

.github/workflows/code-style.yaml
Dockerfile
Makefile

- Remove needing to use ROOT user in Dockerfile builder layer as it's not strictly necessary.
- It was previously needed due to building the binary to `/usr/bin` which is protected from the default user.
- Remove setting GO111MODULE 
- default is on from go v1.17 
* Passing image build should be sufficient
* https://github.com/Kuadrant/authorino/actions/runs/16467329104

refactor: remove needing to use ROOT user in dockerfile
